name: Build packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout repository
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '9.x'

      - name: Install PupNet
        run: dotnet tool update -g KuiperZone.PupNet
      
      - name: Verify PupNet installation
        run: pupnet --version

      - name: Create x64 Appimage
        run: pupnet --runtime linux-x64 --kind appimage

      - name: Create Flatpak
        run: pupnet --runtime linux-x64 --kind flatpak