name: Build packages

on:
  push:
    tags:
      - "v*"
      
jobs:
  Build_x86_64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '9.x'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev libfuse2 libfuse3-3 flatpak flatpak-builder
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install flathub org.gnome.Platform//47 -y
          sudo flatpak install flathub org.gnome.Sdk//47 -y

      - name: Install PupNet
        run: dotnet tool update -g KuiperZone.PupNet

      - name: Create x64 Appimage
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          pupnet --runtime linux-x64 --kind appimage --app-version $VERSION

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v5
        with:
          name: JellyTune-${{ github.ref_name }}.x86_64.appImage
          path: Deploy/JellyTune*.AppImage

      - name: Create Flatpak
        run:  |
          VERSION=${GITHUB_REF_NAME#v}
          pupnet --runtime linux-x64 --kind flatpak --app-version $VERSION

      - name: Upload flatpak artifact
        uses: actions/upload-artifact@v5
        with:
          name: JellyTune-${{ github.ref_name }}.x86_64.flatpak
          path: Deploy/JellyTune-*.flatpak

  Build_arm64:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '9.x'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev libfuse2 libfuse3-3 flatpak flatpak-builder
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-aarch64.AppImage
          chmod +x appimagetool-aarch64.AppImage
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install flathub org.gnome.Platform//47 -y
          sudo flatpak install flathub org.gnome.Sdk//47 -y

      - name: Install PupNet
        run: dotnet tool update -g KuiperZone.PupNet

      - name: Create arm64 Appimage
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          pupnet --runtime linux-arm64 --kind appimage --app-version $VERSION

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v5
        with:
          name: JellyTune-${{ github.ref_name }}.aarch64.appImage
          path: Deploy/JellyTune*.AppImage

      - name: Create Flatpak
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          pupnet --runtime linux-arm64 --kind flatpak --app-version $VERSION

      - name: Upload flatpak artifact
        uses: actions/upload-artifact@v5
        with:
          name: JellyTune-${{ github.ref_name }}.aarch64.flatpak
          path: Deploy/JellyTune-*.flatpak
          
  Create_Release:
    needs: [Build_x86_64, Build_arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: [write, read]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: JellyTune ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload x86_64 appImage
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/JellyTune-${{ github.ref_name }}.x86_64.appImage
          asset_name: JellyTune-${{ github.ref_name }}.x86_64.appImage
          asset_content_type: application/octet-stream
          
      - name: Upload x86_64 flatpak
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/JellyTune-${{ github.ref_name }}.x86_64.flatpak
          asset_name: JellyTune-${{ github.ref_name }}.x86_64.flatpak
          asset_content_type: application/octet-stream

      - name: Upload aarch64 appImage
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/JellyTune-${{ github.ref_name }}.aarch64.appImage
          asset_name: JellyTune-${{ github.ref_name }}.aarch64.appImage
          asset_content_type: application/octet-stream
          
      - name: Upload aarch64 flatpak
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/JellyTune-${{ github.ref_name }}.aarch64.flatpak
          asset_name: JellyTune-${{ github.ref_name }}.aarch64.flatpak
          asset_content_type: application/octet-stream

