name: Build packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout repository
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '9.x'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev libfuse2 libfuse3-3 flatpak flatpak-builder
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install flathub org.gnome.Platform//47 -y
          sudo flatpak install flathub org.gnome.Sdk//47 -y

      - name: Install PupNet
        run: dotnet tool update -g KuiperZone.PupNet

      - name: Create x64 Appimage
        run: pupnet --runtime linux-x64 --kind appimage

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v3
        with:
          name: JellyTune-AppImage
          path: Deploy/JellyTune*.AppImage

      - name: Create Flatpak
        run: pupnet --runtime linux-x64 --kind flatpak

      - name: Upload flatpak artifact
        uses: actions/upload-artifact@v3
        with:
          name: JellyTune-AppImage
          path: Deploy/JellyTune-*.flatpak