name: Build packages

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

env:
  JELLYTUNE_VERSION: 1.0.${{ github.run_number }}

jobs:

  Build_x86_64:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '9.x'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev libfuse2 libfuse3-3 flatpak flatpak-builder
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install flathub org.gnome.Platform//47 -y
          sudo flatpak install flathub org.gnome.Sdk//47 -y

      - name: Install PupNet
        run: dotnet tool update -g KuiperZone.PupNet

      - name: Create x64 Appimage
        run: pupnet --runtime linux-x64 --kind appimage --app-version $JELLYTUNE_VERSION

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v5
        with:
          name: JellyTune-${{ env.JELLYTUNE_VERSION }}.x86_64.appImage
          path: Deploy/JellyTune*.AppImage

      - name: Create Flatpak
        run: pupnet --runtime linux-x64 --kind flatpak --app-version $JELLYTUNE_VERSION

      - name: Upload flatpak artifact
        uses: actions/upload-artifact@v5
        with:
          name: JellyTune-${{ env.JELLYTUNE_VERSION }}.x86_64.flatpak
          path: Deploy/JellyTune-*.flatpak


  Build_arm64:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '9.x'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev libfuse2 libfuse3-3 flatpak flatpak-builder
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-aarch64.AppImage
          chmod +x appimagetool-aarch64.AppImage
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install flathub org.gnome.Platform//47 -y
          sudo flatpak install flathub org.gnome.Sdk//47 -y

      - name: Install PupNet
        run: dotnet tool update -g KuiperZone.PupNet

      - name: Create arm64 Appimage
        run: pupnet --runtime linux-arm64 --kind appimage --app-version $JELLYTUNE_VERSION

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v5
        with:
          name: JellyTune-${{ env.JELLYTUNE_VERSION }}.aarch64.appImage
          path: Deploy/JellyTune*.AppImage

      - name: Create Flatpak
        run: pupnet --runtime linux-arm64 --kind flatpak --app-version $JELLYTUNE_VERSION

      - name: Upload flatpak artifact
        uses: actions/upload-artifact@v5
        with:
          name: JellyTune-${{ env.JELLYTUNE_VERSION }}.aarch64.flatpak
          path: Deploy/JellyTune-*.flatpak

  Create_Release: 
    needs: [Build_x86_64, Build_arm64] 
    runs-on: ubuntu-latest
    steps: 
      - name: Download all artifacts
        uses: actions/download-artifact@v4 
        with: 
          path: artifacts
        

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with: 
          tag_name: v${{ env.JELLYTUNE_VERSION }}
          name: JellyTune v${{ env.JELLYTUNE_VERSION }}
          body: | 
            JellyTune version ${{ env.JELLYTUNE_VERSION }}.
          files: artifacts/**/* 
      
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
